server:
  port: 8080

spring:
  datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://localhost:3306/test
   username: root
   password: 123456



# thymeleaf configeration start
#spring:
  tymeleaf:
    model: HTML5
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
    cache: false
# thymeleaf configeration end